import { CentralizedAIService } from '../../src/modules/ai/ai.service';
import type { AIClient, ExplanationInput } from '../../src/modules/ai/ai.types';

// Mock the AIClient
const mockGenerateText = jest.fn();
const mockClient: AIClient = {
  generateText: mockGenerateText,
};

describe('CentralizedAIService', () => {
  let aiService: CentralizedAIService;

  beforeEach(() => {
    jest.clearAllMocks();
    aiService = new CentralizedAIService(mockClient);
    
    // Default to valid JSON
    mockGenerateText.mockResolvedValue('{"summary":"Test summary generated by AI"}');
  });

  describe('generateOpportunityExplanation', () => {
    const input: ExplanationInput = {
      opportunityTitle: 'Test Opportunity',
      organization: 'Test Org',
      type: 'INTERNSHIP',
      matchingSkills: ['Node.js'],
      gapSkills: ['React'],
      gapSeverity: 'minor',
      careerAlignment: 'direct',
      compatibilityScore: 0.8,
    };

    it('builds the prompt and calls the client', async () => {
      const result = await aiService.generateOpportunityExplanation(input);
      
      expect(mockGenerateText).toHaveBeenCalled();
      expect(result.success).toBe(true);
      expect(result.summary).toBe('Test summary generated by AI');
    });

    it('returns success:false on invalid JSON', async () => {
      mockGenerateText.mockResolvedValue('Not a json string');
      
      const result = await aiService.generateOpportunityExplanation(input);
      
      expect(result.success).toBe(false);
      expect(result.summary).toBeUndefined();
    });

    it('returns success:false when generated JSON fails schema validation', async () => {
      // Schema requires 'summary'
      mockGenerateText.mockResolvedValue('{"other_field":"val"}');
      
      const result = await aiService.generateOpportunityExplanation(input);
      
      expect(result.success).toBe(false);
      expect(result.summary).toBeUndefined();
    });

    it('returns success:false when client.generateText throws', async () => {
      mockGenerateText.mockRejectedValue(new Error('Network error'));
      
      const result = await aiService.generateOpportunityExplanation(input);
      
      expect(result.success).toBe(false);
      expect(result.summary).toBeUndefined();
    });
  });
});
